import Foundation

class CardLoader {
    /// Oyun akışı için gerekli zar ve çark kartları (demo soru/görev kartları yok).
    static func loadSystemCards() -> [GameCard] {
        loadDiceAndWheelCards()
    }

    @available(*, deprecated, message: "Use CardCatalog.loadForGameplay()")
    static func loadSeedCards() -> [GameCard] {
        loadDiceAndWheelCards() + loadDeprecatedDemoCards()
    }

    private static func loadDiceAndWheelCards() -> [GameCard] {
        return [
            GameCard(
                id: "sys_wheel_1",
                title: "Çark Görevi 1",
                type: .wheel,
                phase: .wheel,
                intensity: 3,
                minIntensity: .soft,
                maxIntensity: .hot,
                durationSeconds: 45,
                actorRule: .wheelSelected,
                targetRule: .none,
                usesWheel: true,
                text: "{actor}, çark tarafından seçildi ve {duration} süresince görev yapacak.",
                relatedPenaltyId: "penalty_wheel_1",
                refusalPenaltyId: "penalty_refusal_1"
            ),
            GameCard(
                id: "sys_wheel_2",
                title: "Çark Görevi 2",
                type: .wheel,
                phase: .wheel,
                intensity: 4,
                minIntensity: .hot,
                maxIntensity: .hardcore,
                durationSeconds: 60,
                actorRule: .wheelSelected,
                targetRule: .randomOther,
                usesWheel: true,
                text: "{actor}, {target} ile birlikte çark görevini tamamlayacak.",
                relatedPenaltyId: "penalty_wheel_1",
                refusalPenaltyId: "penalty_refusal_1"
            ),
            GameCard(
                id: "sys_dice_question_1",
                title: "Kader — Soru 1",
                type: .dice,
                phase: .dice,
                intensity: 2,
                minIntensity: .soft,
                maxIntensity: .medium,
                durationSeconds: 30,
                actorRule: .currentPlayer,
                targetRule: .none,
                text: "{actor}, kader sorusunu {duration} içinde cevaplayacak.",
                relatedPenaltyId: "penalty_question_1",
                refusalPenaltyId: "penalty_refusal_1",
                fateCategory: .question
            ),
            GameCard(
                id: "sys_dice_question_2",
                title: "Kader — Soru 2",
                type: .dice,
                phase: .dice,
                intensity: 4,
                minIntensity: .hot,
                maxIntensity: .hardcore,
                durationSeconds: 45,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                text: "{actor}, {target} hakkında cesur bir soruyu cevaplayacak.",
                relatedPenaltyId: "penalty_question_1",
                refusalPenaltyId: "penalty_refusal_1",
                fateCategory: .question
            ),
            GameCard(
                id: "sys_dice_touch_1",
                title: "Kader — Dokunuş 1",
                type: .dice,
                phase: .dice,
                intensity: 2,
                minIntensity: .soft,
                maxIntensity: .medium,
                durationSeconds: 40,
                actorRule: .currentPlayer,
                targetRule: .none,
                text: "{actor}, {duration} süresince hafif bir dokunuş görevi yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_1",
                fateCategory: .touch
            ),
            GameCard(
                id: "sys_dice_touch_2",
                title: "Kader — Dokunuş 2",
                type: .dice,
                phase: .dice,
                intensity: 4,
                minIntensity: .medium,
                maxIntensity: .hardcore,
                durationSeconds: 60,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                text: "{actor}, {target} ile {duration} süresince dokunuş görevi yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_2",
                fateCategory: .touch
            ),
            GameCard(
                id: "sys_dice_role_1",
                title: "Kader — Rol 1",
                type: .dice,
                phase: .dice,
                intensity: 3,
                minIntensity: .medium,
                maxIntensity: .hot,
                durationSeconds: 50,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                text: "{actor} ve {target}, rol kartı görevini {duration} içinde yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_2",
                fateCategory: .role
            ),
            GameCard(
                id: "sys_dice_role_2",
                title: "Kader — Rol 2",
                type: .dice,
                phase: .dice,
                intensity: 5,
                minIntensity: .hardcore,
                maxIntensity: .hardcore,
                durationSeconds: 75,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                text: "{actor} ve {target}, yoğun rol görevini tamamlayacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_1",
                fateCategory: .role
            ),
            GameCard(
                id: "sys_dice_dare_1",
                title: "Kader — Cesaret 1",
                type: .dice,
                phase: .dice,
                intensity: 3,
                minIntensity: .medium,
                maxIntensity: .hot,
                durationSeconds: 45,
                actorRule: .currentPlayer,
                targetRule: .none,
                text: "{actor}, cesaret görevini {duration} içinde tamamlayacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_1",
                fateCategory: .dare
            ),
            GameCard(
                id: "sys_dice_dare_2",
                title: "Kader — Cesaret 2",
                type: .dice,
                phase: .dice,
                intensity: 5,
                minIntensity: .hot,
                maxIntensity: .hardcore,
                durationSeconds: 70,
                actorRule: .currentPlayer,
                targetRule: .none,
                text: "{actor}, en cesur kader görevini {duration} süresince yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_1",
                fateCategory: .dare
            ),
            GameCard(
                id: "sys_dice_partner_1",
                title: "Kader — Partner 1",
                type: .dice,
                phase: .dice,
                intensity: 3,
                minIntensity: .soft,
                maxIntensity: .medium,
                durationSeconds: 50,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                requiresTargetConsent: true,
                text: "{actor}, {target} ile partner görevini {duration} içinde yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_2",
                fateCategory: .partner
            ),
            GameCard(
                id: "sys_dice_partner_2",
                title: "Kader — Partner 2",
                type: .dice,
                phase: .dice,
                intensity: 5,
                minIntensity: .hot,
                maxIntensity: .hardcore,
                durationSeconds: 80,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                requiresTargetConsent: true,
                text: "{actor} ve {target}, yoğun partner görevini tamamlayacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_2",
                fateCategory: .partner
            )
        ]
    }

    private static func loadDeprecatedDemoCards() -> [GameCard] {
        return [
            GameCard(
                title: "Cesur Soru 1",
                type: .question,
                phase: .boldQuestion,
                intensity: 3,
                minIntensity: .soft,
                maxIntensity: .hardcore,
                durationSeconds: 30,
                actorRule: .currentPlayer,
                targetRule: .none,
                text: "{actor}, bir soruyu {duration} içinde cevaplayacak.",
                relatedPenaltyId: "penalty_question_1",
                refusalPenaltyId: "penalty_refusal_1"
            ),
            GameCard(
                title: "Cesur Soru 2",
                type: .question,
                phase: .boldQuestion,
                intensity: 4,
                minIntensity: .medium,
                maxIntensity: .hardcore,
                durationSeconds: 45,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                text: "{actor}, {target} hakkında bir soruyu cevaplayacak.",
                answers: ["Evet", "Hayır"],
                triggerAnswer: "Hayır",
                surpriseTask: SurpriseTask(
                    text: "{actor}, şimdi {target} için 30 saniyede sürpriz görev yapacak!",
                    durationSeconds: 30
                ),
                relatedPenaltyId: "penalty_question_1",
                refusalPenaltyId: "penalty_refusal_1"
            ),
            GameCard(
                title: "Sürpriz Soru 1",
                type: .surpriseQuestion,
                phase: .surpriseQuestion,
                intensity: 3,
                minIntensity: .soft,
                maxIntensity: .hardcore,
                durationSeconds: 40,
                actorRule: .currentPlayer,
                targetRule: .none,
                text: "{actor}, {duration} içinde sürpriz bir soruya cevap verecek.",
                relatedPenaltyId: "penalty_question_1",
                refusalPenaltyId: "penalty_refusal_1"
            ),
            GameCard(
                title: "Süreli Görev 1",
                type: .task,
                phase: .timedTask,
                intensity: 3,
                minIntensity: .soft,
                maxIntensity: .medium,
                durationSeconds: 50,
                actorRule: .currentPlayer,
                targetRule: .none,
                text: "{actor}, {duration} süresince bir görev yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_2"
            ),
            GameCard(
                title: "Partner Görevi",
                type: .task,
                phase: .timedTask,
                intensity: 4,
                minIntensity: .medium,
                maxIntensity: .hardcore,
                durationSeconds: 60,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                requiresTargetConsent: true,
                text: "{actor}, {target} ile birlikte {duration} süresince bir görev yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_2"
            ),
            GameCard(
                title: "Çark Görevi 1",
                type: .wheel,
                phase: .wheel,
                intensity: 3,
                minIntensity: .soft,
                maxIntensity: .hot,
                durationSeconds: 45,
                actorRule: .wheelSelected,
                targetRule: .none,
                usesWheel: true,
                text: "{actor}, çark tarafından seçildi ve {duration} süresince görev yapacak.",
                relatedPenaltyId: "penalty_wheel_1",
                refusalPenaltyId: "penalty_refusal_1"
            ),
            GameCard(
                title: "Çark Görevi 2",
                type: .wheel,
                phase: .wheel,
                intensity: 4,
                minIntensity: .hot,
                maxIntensity: .hardcore,
                durationSeconds: 60,
                actorRule: .wheelSelected,
                targetRule: .randomOther,
                usesWheel: true,
                text: "{actor}, {target} ile birlikte çark görevini tamamlayacak.",
                relatedPenaltyId: "penalty_wheel_1",
                refusalPenaltyId: "penalty_refusal_1"
            ),
            GameCard(
                title: "Kader — Soru 1",
                type: .dice,
                phase: .dice,
                intensity: 2,
                minIntensity: .soft,
                maxIntensity: .medium,
                durationSeconds: 30,
                actorRule: .currentPlayer,
                targetRule: .none,
                text: "{actor}, kader sorusunu {duration} içinde cevaplayacak.",
                relatedPenaltyId: "penalty_question_1",
                refusalPenaltyId: "penalty_refusal_1",
                fateCategory: .question
            ),
            GameCard(
                title: "Kader — Soru 2",
                type: .dice,
                phase: .dice,
                intensity: 4,
                minIntensity: .hot,
                maxIntensity: .hardcore,
                durationSeconds: 45,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                text: "{actor}, {target} hakkında cesur bir soruyu cevaplayacak.",
                relatedPenaltyId: "penalty_question_1",
                refusalPenaltyId: "penalty_refusal_1",
                fateCategory: .question
            ),
            GameCard(
                title: "Kader — Dokunuş 1",
                type: .dice,
                phase: .dice,
                intensity: 2,
                minIntensity: .soft,
                maxIntensity: .medium,
                durationSeconds: 40,
                actorRule: .currentPlayer,
                targetRule: .none,
                text: "{actor}, {duration} süresince hafif bir dokunuş görevi yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_1",
                fateCategory: .touch
            ),
            GameCard(
                title: "Kader — Dokunuş 2",
                type: .dice,
                phase: .dice,
                intensity: 4,
                minIntensity: .medium,
                maxIntensity: .hardcore,
                durationSeconds: 60,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                text: "{actor}, {target} ile {duration} süresince dokunuş görevi yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_2",
                fateCategory: .touch
            ),
            GameCard(
                title: "Kader — Rol 1",
                type: .dice,
                phase: .dice,
                intensity: 3,
                minIntensity: .medium,
                maxIntensity: .hot,
                durationSeconds: 50,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                text: "{actor} ve {target}, rol kartı görevini {duration} içinde yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_2",
                fateCategory: .role
            ),
            GameCard(
                title: "Kader — Rol 2",
                type: .dice,
                phase: .dice,
                intensity: 5,
                minIntensity: .hardcore,
                maxIntensity: .hardcore,
                durationSeconds: 75,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                text: "{actor} ve {target}, yoğun rol görevini tamamlayacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_1",
                fateCategory: .role
            ),
            GameCard(
                title: "Kader — Cesaret 1",
                type: .dice,
                phase: .dice,
                intensity: 3,
                minIntensity: .medium,
                maxIntensity: .hot,
                durationSeconds: 45,
                actorRule: .currentPlayer,
                targetRule: .none,
                text: "{actor}, cesaret görevini {duration} içinde tamamlayacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_1",
                fateCategory: .dare
            ),
            GameCard(
                title: "Kader — Cesaret 2",
                type: .dice,
                phase: .dice,
                intensity: 5,
                minIntensity: .hot,
                maxIntensity: .hardcore,
                durationSeconds: 70,
                actorRule: .currentPlayer,
                targetRule: .none,
                text: "{actor}, en cesur kader görevini {duration} süresince yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_1",
                fateCategory: .dare
            ),
            GameCard(
                title: "Kader — Partner 1",
                type: .dice,
                phase: .dice,
                intensity: 3,
                minIntensity: .soft,
                maxIntensity: .medium,
                durationSeconds: 50,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                requiresTargetConsent: true,
                text: "{actor}, {target} ile partner görevini {duration} içinde yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_2",
                fateCategory: .partner
            ),
            GameCard(
                title: "Kader — Partner 2",
                type: .dice,
                phase: .dice,
                intensity: 5,
                minIntensity: .hot,
                maxIntensity: .hardcore,
                durationSeconds: 80,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                requiresTargetConsent: true,
                text: "{actor} ve {target}, yoğun partner görevini tamamlayacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_2",
                fateCategory: .partner
            ),
            GameCard(
                title: "Rol Kartı 1",
                type: .roleDuo,
                phase: .roleDuo,
                intensity: 4,
                minIntensity: .hot,
                maxIntensity: .hardcore,
                durationSeconds: 50,
                actorRule: .currentPlayer,
                targetRule: .randomOther,
                text: "{actor} ve {target}, rol kartı görevini yapacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_2"
            ),
            GameCard(
                title: "Final Focus 1",
                type: .task,
                phase: .finalFocus,
                intensity: 5,
                minIntensity: .hardcore,
                maxIntensity: .hardcore,
                durationSeconds: 90,
                actorRule: .currentPlayer,
                targetRule: .allPlayers,
                text: "{actor}, final görevini {duration} süresince tamamlayacak.",
                relatedPenaltyId: "penalty_task_1",
                refusalPenaltyId: "penalty_refusal_1"
            )
        ]
    }

    static func loadSeedPenalties() -> [PenaltyCard] {
        PenaltyCatalog.loadSeedPenalties()
    }
}
